---
- name: Create systemd unit file
  template:
    src: geth.service.j2
    dest: /etc/systemd/system/geth.service
    mode: 0400
    owner: '{{geth_user}}'
    group: '{{geth_group}}'
  notify: restart geth
  tags: systemd

- name: Enable systemd service
  systemd:
    name: geth.service
    state: stopped
    enabled: true
    daemon_reload: true
  tags: systemd
